FROM node:20-alpine AS build
ENV NODE_OPTIONS="--max-old-space-size=2048"

# Argumentos de construcción
ARG VITE_GOOGLE_DRIVE_CLIENT_ID
ARG VITE_GOOGLE_DRIVE_API_KEY
ARG VITE_GOOGLE_DRIVE_CLIENT_SECRET
ARG VITE_DRIVE_TEMPLATES_FOLDER_ID
ARG VITE_DRIVE_DESTINATION_FOLDER_ID
ARG VITE_GOOGLE_SHEETS_LOG_ID
ARG VITE_PREVIEW_API_URL
ARG GEMINI_API_KEY
ARG VITE_DEEPSEEK_API_KEY
ARG VITE_STORAGE_MODE
ARG VITE_NEXTCLOUD_URL
ARG VITE_NEXTCLOUD_CLIENT_ID
ARG VITE_NEXTCLOUD_CLIENT_SECRET
ARG VITE_NEXTCLOUD_TEMPLATES_PATH
ARG VITE_NEXTCLOUD_DESTINATION_PATH

# Ensuciar ENV para que el build los vea
ENV VITE_GOOGLE_DRIVE_CLIENT_ID=$VITE_GOOGLE_DRIVE_CLIENT_ID
ENV VITE_GOOGLE_DRIVE_API_KEY=$VITE_GOOGLE_DRIVE_API_KEY
ENV VITE_GOOGLE_DRIVE_CLIENT_SECRET=$VITE_GOOGLE_DRIVE_CLIENT_SECRET
ENV VITE_DRIVE_TEMPLATES_FOLDER_ID=$VITE_DRIVE_TEMPLATES_FOLDER_ID
ENV VITE_DRIVE_DESTINATION_FOLDER_ID=$VITE_DRIVE_DESTINATION_FOLDER_ID
ENV VITE_GOOGLE_SHEETS_LOG_ID=$VITE_GOOGLE_SHEETS_LOG_ID
ENV VITE_PREVIEW_API_URL=$VITE_PREVIEW_API_URL
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV VITE_DEEPSEEK_API_KEY=$VITE_DEEPSEEK_API_KEY
ENV VITE_STORAGE_MODE=$VITE_STORAGE_MODE
ENV VITE_NEXTCLOUD_URL=$VITE_NEXTCLOUD_URL
ENV VITE_NEXTCLOUD_CLIENT_ID=$VITE_NEXTCLOUD_CLIENT_ID
ENV VITE_NEXTCLOUD_CLIENT_SECRET=$VITE_NEXTCLOUD_CLIENT_SECRET
ENV VITE_NEXTCLOUD_TEMPLATES_PATH=$VITE_NEXTCLOUD_TEMPLATES_PATH
ENV VITE_NEXTCLOUD_DESTINATION_PATH=$VITE_NEXTCLOUD_DESTINATION_PATH

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Etapa de Producción
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html

RUN echo 'server { \
    listen 80; \
    client_max_body_size 100M; \
    location / { \
    root /usr/share/nginx/html; \
    index index.html index.htm; \
    try_files $uri $uri/ /index.html; \
    } \
    location /api-preview/ { \
    proxy_pass http://backend:8000/; \
    proxy_http_version 1.1; \
    proxy_set_header Upgrade $http_upgrade; \
    proxy_set_header Connection "upgrade"; \
    proxy_set_header Host $host; \
    proxy_set_header X-Real-IP $remote_addr; \
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; \
    proxy_set_header X-Forwarded-Proto $scheme; \
    proxy_read_timeout 300; \
    proxy_connect_timeout 300; \
    proxy_send_timeout 300; \
    } \
    }' > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
